apiVersion: v1
kind: Namespace
metadata:
  name: limiter-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: limiter-pod # Base POD name
  namespace: limits-system
spec:
  selector:
    matchLabels:
      app: limiter # Selector for POD name search.
  template:
    metadata:
      labels:
        app: limiter
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: limits-api
          image: limiter-api-image
          ports:
            - name: limits-api
              containerPort: 3000
            - name: l-api-debug
              containerPort: 4000
          readinessProbe: # readiness probes mark the service available to accept traffic.
            httpGet:
              path: /debug/readiness
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
            httpGet:
              path: /debug/liveness
              port: 4000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_NAMESPACE_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: KUBERNETES_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          # metrics container configuration
---
apiVersion: v1
kind: Service
metadata:
  name: limiter-service
  namespace: limits-system
spec:
  type: ClusterIP
  selector:
    app: limiter
  ports:
    - name: limits-api
      port: 3000
      targetPort: limits-api
    - name: l-api-debug
      port: 4000
      targetPort: l-api-debug