apiVersion: apps/v1
kind: Deployment
metadata:
  name: limiter-pod
  namespace: limits-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: limiter
  template:
    metadata:
      labels:
        app: limiter
    spec:
      containers:
        # lola-api container configuration
        - name: limits-api
          resources:
            limits:
              cpu: "2000m" # Up to 2 full cores
            requests:
              cpu: "1000m" # Use 1 full cores