apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/limiter-pod/
patchesStrategicMerge:
- ./kind-limiter-patch.yaml
images:
- name: limiter-api-image
  newName: limiter-api-amd64
  newTag: "1.0"
